=== marcelobarrosalmeida/avr32fs/DTD/ALFS.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
       ALFS :    Document Type Definition
       Version : 3.1
       Author:   V. Dzuba
       Updates:  Kevin P. Fleming
       Date:     July 3, 2004

       The current version of the DTD is available at:
             http://www.linuxfromscratch.org/alfs/downloads/stable

       The current version of its documentation is available at:
             http://www.linuxfromscratch.org/alfs/view/dtd

       This DTD is published under both BSD and GNU licenses.
-->

<!ENTITY lt     "&#38;#60;"> 
<!ENTITY gt     "&#62;"> 
<!ENTITY amp    "&#38;#38;"> 
<!ENTITY apos   "&#39;"> 
<!ENTITY quot   "&#34;"> 

<!ENTITY % ops "configure | copy | download | execute | link | make | mkdir | move | ownership | package | patch | permissions | remove | search_replace | stage | textdump | unpack">

<!ELEMENT alfs           ((%ops; | include)+)>
<!ATTLIST alfs
          base           CDATA #IMPLIED
          version        CDATA #FIXED "3.1"
	  xml:base	 CDATA #IMPLIED
	  xmlns:xi	 CDATA #IMPLIED>

<!ELEMENT archive        (#PCDATA)>

<!ELEMENT base           (#PCDATA)>

<!ELEMENT configure      ((param | prefix)*)>
<!ATTLIST configure
          base           CDATA #IMPLIED
          command        CDATA #IMPLIED>

<!ELEMENT content        (#PCDATA)>

<!ELEMENT copy           (option*, source+, destination)>
<!ATTLIST copy
          base           CDATA #IMPLIED>

<!ELEMENT description    (para | list)*>

<!ELEMENT destination    (#PCDATA)>

<!ELEMENT digest         (#PCDATA)>
<!ATTLIST digest         
          type           CDATA     "md5">

<!ELEMENT download       (file, url*, destination, digest?)>

<!ELEMENT environment    (variable+)>
<!ATTLIST environment
          mode           (append | prepend) #IMPLIED>

<!ELEMENT execute        ((param | prefix)*)>
<!ATTLIST execute
          base           CDATA #IMPLIED
          command        CDATA #REQUIRED>

<!ELEMENT file           (#PCDATA)>

<!ELEMENT find           (#PCDATA)>

<!ELEMENT include        EMPTY>
<!ATTLIST include
          href           CDATA #REQUIRED>

<!ELEMENT item           (#PCDATA)>

<!ELEMENT link           (option*, target+, name)>
<!ATTLIST link
          base           CDATA #IMPLIED
          type           CDATA #IMPLIED>

<!ELEMENT list           (item | list)+>
<!ATTLIST list
          type           (bullet | number) "bullet">

<!ELEMENT make           ((param | prefix)*)>
<!ATTLIST make
          base           CDATA #IMPLIED>

<!ELEMENT mkdir          (option?, permissions?, name+)>
<!ATTLIST mkdir
          base           CDATA #IMPLIED>
          
<!ELEMENT move           (option?, source+, destination)>
<!ATTLIST move
          base           CDATA #IMPLIED>

<!ELEMENT name           (#PCDATA)>

<!ELEMENT option         (#PCDATA)>

<!ELEMENT ownership      (option?, name+)>
<!ATTLIST ownership
          base           CDATA #IMPLIED
          user           CDATA #IMPLIED
          group          CDATA #IMPLIED>
          
<!ELEMENT package        (packageinfo?, stage+)>
<!ATTLIST package
          name           CDATA #REQUIRED
          version        CDATA #REQUIRED>

<!ELEMENT packageinfo    (description?, requires*, utilizes*)>

<!ELEMENT para           (#PCDATA)>

<!ELEMENT param          (#PCDATA)>

<!ELEMENT patch          ((param | prefix)+)>
<!ATTLIST patch
          base           CDATA #IMPLIED>

<!ELEMENT permissions    (option?, name*)>
<!ATTLIST permissions
          base           CDATA #IMPLIED
          mode           CDATA #REQUIRED>

<!ELEMENT prefix         (#PCDATA)>

<!ELEMENT reference      (#PCDATA)>

<!ELEMENT remove         (#PCDATA)>

<!ELEMENT replace        (#PCDATA)>

<!ELEMENT requires       (name, version*)>

<!ELEMENT root           (#PCDATA)>

<!ELEMENT search_replace (file, find, replace)>
<!ATTLIST search_replace
          base           CDATA #IMPLIED>

<!ELEMENT source         (#PCDATA)>

<!ELEMENT stage          (stageinfo?, (alfs | %ops;)*)>
<!ATTLIST stage
          name           CDATA #IMPLIED>

<!ELEMENT stageinfo      (root?, user?, environment?, base?)>

<!ELEMENT target         (#PCDATA)>

<!ELEMENT textdump       (file, content)>
<!ATTLIST textdump
          base           CDATA #IMPLIED
          mode           CDATA #IMPLIED>

<!ELEMENT unpack         (digest?, reference*, archive, destination)>

<!ELEMENT url            (#PCDATA)>

<!ELEMENT user           (#PCDATA)>

<!ELEMENT utilizes       (name, version*)>

<!ELEMENT variable       (#PCDATA)>
<!ATTLIST variable
          name           CDATA #REQUIRED
          mode           CDATA #IMPLIED>

<!ELEMENT version        (#PCDATA)>
<!ATTLIST version
          condition      (eq | ne | gt | ge | lt | le) #REQUIRED>

=== marcelobarrosalmeida/avr32fs/stage1/skeleton.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <stage name="Basic skeleton">
    <remove>&root_dir;</remove>
    <remove>&build_dir;</remove>
    <mkdir>
      <option>parents</option>
      <name>&root_dir;</name>
    </mkdir>
    <mkdir>
      <option>parents</option>
      <name>&build_dir;</name>
    </mkdir>
    <mkdir base="&root_dir;">
      <option>parents</option>
      <name>bin</name>
      <name>boot</name>
      <name>dev</name>
      <name>home/avr32</name>
      <name>home/ftp</name>
      <name>lib</name>
      <name>media/dataflash</name>
      <name>media/sdcard</name>
      <name>mnt</name>
      <name>proc</name>
      <name>root</name>
      <name>sbin</name>
      <name>sys</name>
      <name>tmp</name>
      <name>usr</name>
      <name>var</name>
      <name>etc</name>
      <name>config</name>
    </mkdir>
    <mkdir base="&root_dir;/etc">
      <option>parents</option>
      <name>init.d</name>
      <name>network</name>
      <name>default</name>
    </mkdir>
    <mkdir base="&root_dir;/dev">
      <option>parents</option>
      <name>pts</name>
      <name>chm</name>
    </mkdir>
    <mkdir base="&root_dir;/usr">
      <option>parents</option>
      <name>bin</name>
      <name>include</name>
      <name>lib</name>
      <name>sbin</name>
      <name>share</name>
      <name>src</name>
    </mkdir>
    <mkdir base="&root_dir;/usr/share">
      <option>parents</option>
      <name>doc</name>
      <name>info</name>
      <name>locale</name>
      <name>man</name>
      <name>misc</name>
      <name>terminfo</name>
      <name>zoneinfo</name>
    </mkdir>
    <mkdir base="&root_dir;/usr/share/man">
      <option>parents</option>
      <name>man1</name>
      <name>man2</name>
      <name>man3</name>
      <name>man4</name>
      <name>man5</name>
      <name>man6</name>
      <name>man7</name>
      <name>man8</name>
    </mkdir>
    <mkdir base="&root_dir;/var">
      <option>parents</option>
      <name>lock</name>
      <name>log</name>
      <name>mail</name>
      <name>run</name>
      <name>spool</name>
      <name>tmp</name>
      <name>cache</name>
      <name>lib/misc</name>
      <name>www</name>
    </mkdir>
    <permissions base="&root_dir;" mode="0750">
      <name>root</name>
    </permissions>
    <permissions base="&root_dir;" mode="1777">
      <name>tmp</name>
      <name>var/tmp</name>
    </permissions>
  </stage>
</alfs>

=== marcelobarrosalmeida/avr32fs/trunk/stage2/dropbear.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <package name="dropbear" version="&dropbear-version;">
    <stage name="Unpacking">
      <unpack>
        <reference>&repository_url;/&dropbear-package;</reference>
        <archive>&packages_dir;/dropbear/&dropbear-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Patching">
      <stageinfo>
        <base>&build_dir;/&dropbear-directory;</base>
      </stageinfo>
      <patch>
        <param>-p1</param>
        <param>-i &packages_dir;/dropbear/&dropbear-dropbear-add-avr32-to-configure-patch;</param>
      </patch>
    </stage>
    <stage name="Compiling">
      <stageinfo>
        <base>&build_dir;/&dropbear-directory;</base>
        <environment>
          <variable name="CFLAGS">-O2</variable>
        </environment>
      </stageinfo>
      <configure>
        <param>--prefix=/usr</param>
        <param>--host=avr32-linux</param>
      </configure>
      <make>
        <param>PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp"</param>
      </make>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&dropbear-directory;</base>
      </stageinfo>
      <make>
        <param>install</param>
        <param>PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp"</param>
        <param>DESTDIR=&root_dir;/</param>
      </make>
    </stage>
    <!--
    <stage name="Strip">
      <remove>&build_dir;/&dropbear-directory;</remove>
    </stage>
    -->
    <!--
    <stage name="Cleanup">
      <remove>&build_dir;/&dropbear-directory;</remove>
    </stage>
    -->
  </package>
</alfs>
