=== marcelobarrosalmeida/avr32fs/DTD/ALFS.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
       ALFS :    Document Type Definition
       Version : 3.1
       Author:   V. Dzuba
       Updates:  Kevin P. Fleming
       Date:     July 3, 2004

       The current version of the DTD is available at:
             http://www.linuxfromscratch.org/alfs/downloads/stable

       The current version of its documentation is available at:
             http://www.linuxfromscratch.org/alfs/view/dtd

       This DTD is published under both BSD and GNU licenses.
-->

<!ENTITY lt     "&#38;#60;"> 
<!ENTITY gt     "&#62;"> 
<!ENTITY amp    "&#38;#38;"> 
<!ENTITY apos   "&#39;"> 
<!ENTITY quot   "&#34;"> 

<!ENTITY % ops "configure | copy | download | execute | link | make | mkdir | move | ownership | package | patch | permissions | remove | search_replace | stage | textdump | unpack">

<!ELEMENT alfs           ((%ops; | include)+)>
<!ATTLIST alfs
          base           CDATA #IMPLIED
          version        CDATA #FIXED "3.1"
	  xml:base	 CDATA #IMPLIED
	  xmlns:xi	 CDATA #IMPLIED>

<!ELEMENT archive        (#PCDATA)>

<!ELEMENT base           (#PCDATA)>

<!ELEMENT configure      ((param | prefix)*)>
<!ATTLIST configure
          base           CDATA #IMPLIED
          command        CDATA #IMPLIED>

<!ELEMENT content        (#PCDATA)>

<!ELEMENT copy           (option*, source+, destination)>
<!ATTLIST copy
          base           CDATA #IMPLIED>

<!ELEMENT description    (para | list)*>

<!ELEMENT destination    (#PCDATA)>

<!ELEMENT digest         (#PCDATA)>
<!ATTLIST digest         
          type           CDATA     "md5">

<!ELEMENT download       (file, url*, destination, digest?)>

<!ELEMENT environment    (variable+)>
<!ATTLIST environment
          mode           (append | prepend) #IMPLIED>

<!ELEMENT execute        ((param | prefix)*)>
<!ATTLIST execute
          base           CDATA #IMPLIED
          command        CDATA #REQUIRED>

<!ELEMENT file           (#PCDATA)>

<!ELEMENT find           (#PCDATA)>

<!ELEMENT include        EMPTY>
<!ATTLIST include
          href           CDATA #REQUIRED>

<!ELEMENT item           (#PCDATA)>

<!ELEMENT link           (option*, target+, name)>
<!ATTLIST link
          base           CDATA #IMPLIED
          type           CDATA #IMPLIED>

<!ELEMENT list           (item | list)+>
<!ATTLIST list
          type           (bullet | number) "bullet">

<!ELEMENT make           ((param | prefix)*)>
<!ATTLIST make
          base           CDATA #IMPLIED>

<!ELEMENT mkdir          (option?, permissions?, name+)>
<!ATTLIST mkdir
          base           CDATA #IMPLIED>
          
<!ELEMENT move           (option?, source+, destination)>
<!ATTLIST move
          base           CDATA #IMPLIED>

<!ELEMENT name           (#PCDATA)>

<!ELEMENT option         (#PCDATA)>

<!ELEMENT ownership      (option?, name+)>
<!ATTLIST ownership
          base           CDATA #IMPLIED
          user           CDATA #IMPLIED
          group          CDATA #IMPLIED>
          
<!ELEMENT package        (packageinfo?, stage+)>
<!ATTLIST package
          name           CDATA #REQUIRED
          version        CDATA #REQUIRED>

<!ELEMENT packageinfo    (description?, requires*, utilizes*)>

<!ELEMENT para           (#PCDATA)>

<!ELEMENT param          (#PCDATA)>

<!ELEMENT patch          ((param | prefix)+)>
<!ATTLIST patch
          base           CDATA #IMPLIED>

<!ELEMENT permissions    (option?, name*)>
<!ATTLIST permissions
          base           CDATA #IMPLIED
          mode           CDATA #REQUIRED>

<!ELEMENT prefix         (#PCDATA)>

<!ELEMENT reference      (#PCDATA)>

<!ELEMENT remove         (#PCDATA)>

<!ELEMENT replace        (#PCDATA)>

<!ELEMENT requires       (name, version*)>

<!ELEMENT root           (#PCDATA)>

<!ELEMENT search_replace (file, find, replace)>
<!ATTLIST search_replace
          base           CDATA #IMPLIED>

<!ELEMENT source         (#PCDATA)>

<!ELEMENT stage          (stageinfo?, (alfs | %ops;)*)>
<!ATTLIST stage
          name           CDATA #IMPLIED>

<!ELEMENT stageinfo      (root?, user?, environment?, base?)>

<!ELEMENT target         (#PCDATA)>

<!ELEMENT textdump       (file, content)>
<!ATTLIST textdump
          base           CDATA #IMPLIED
          mode           CDATA #IMPLIED>

<!ELEMENT unpack         (digest?, reference*, archive, destination)>

<!ELEMENT url            (#PCDATA)>

<!ELEMENT user           (#PCDATA)>

<!ELEMENT utilizes       (name, version*)>

<!ELEMENT variable       (#PCDATA)>
<!ATTLIST variable
          name           CDATA #REQUIRED
          mode           CDATA #IMPLIED>

<!ELEMENT version        (#PCDATA)>
<!ATTLIST version
          condition      (eq | ne | gt | ge | lt | le) #REQUIRED>

=== marcelobarrosalmeida/avr32fs/stage2/zlib.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <package name="zlib" version="&zlib-version;">
    <stage name="Unpacking">
      <unpack>
        <reference>&repository_url;/&zlib-package;</reference>
        <archive>&packages_dir;/zlib/&zlib-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Patching">
    </stage>
    <stage name="Compiling">
      <stageinfo>
        <base>&build_dir;/&zlib-directory;</base>
        <environment>
          <variable name="CC">avr32-linux-gcc</variable>
          <variable name="CFLAGS">-O2</variable>
        </environment>
      </stageinfo>
      <configure>
        <param>--prefix=/usr</param>
        <param>-shared</param>
      </configure>
      <make />
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&zlib-directory;</base>
      </stageinfo>
      <copy>
        <option>force</option>
        <source>libz.so.&zlib-version;</source>
        <destination>&root_dir;/usr/lib</destination>
      </copy>
      <link type="symbolic" base="&root_dir;/usr/lib">
        <target>libz.so.&zlib-version;</target>
        <name>libz.so.1</name>
      </link>
    </stage>
    <!--
    <stage name="Strip">
      <remove>&build_dir;/&zlib-directory;</remove>
    </stage>
    -->
    <!--
    <stage name="Cleanup">
      <remove>&build_dir;/&zlib-directory;</remove>
    </stage>
    -->
  </package>
</alfs>

=== marcelobarrosalmeida/avr32fs/stage1/etcfiles.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <stage name="etc files">
    <stageinfo>
      <base>&root_dir;/etc</base>
    </stageinfo>
    <copy>
      <option>archive</option>
      <source>&skel_dir;/etc/*</source>
      <destination>.</destination>
    </copy>
    <!-- =================================================================== -->
    <textdump>
      <file>passwd</file>
        <content>
          =root:$1$rsjkLsTU$zdulfnYQgyKmN3e0Fiw7C1:0:0:root:/:/bin/ash
          =ftp::50:50:Anonymous FTP user:/home/ftp:/bin/ash
          =www-data:x:51:51:www-data:/var/www:/bin/false
          =sshd:x:110:65534:linux User,,,:/var/run/sshd:/bin/false
          =avr32:$1$iPQqCZth$aB00EMq2M101iRqQU8d4v/:500:100:Linux User,,,:/home/avr32:/bin/ash
          =nobody:x:65534:65534:nobody:/nonexistent:/bin/false
        </content>
    </textdump>
    <!-- =================================================================== -->    
    <textdump>
      <file>group</file>
        <content>
          =root::0:
          =bin:x:1:
          =sys:x:2:
          =tty:x:3:
          =daemon:x:4:
          =ftp::50:
          =www-data::51:
          =users::100:
          =audio::101:
          =nogroup::65534
        </content>
    </textdump>
    <!-- =================================================================== -->    
    <textdump>
      <file>fstab</file>
        <content>
          =/dev/mmcblk0p1   /media/sdcard		    ext2		  defaults		        0 0
          =/dev/mtdblock3   /media/dataflash  	  jffs2		  defaults 		        0	0 
          =proc             /proc	 			        proc		  defaults		        0	0
          =none             /sys	 			          sysfs		  defaults		        0	0
          =none             /dev/pts 			      devpts  	defaults		        0	0
          =tmpfs            /dev/shm 			      tmpfs	 	  defaults		        0	0
          =none             /var/log 			      tmpfs    	defaults		        0	0
          =none             /tmp     			      tmpfs    	defaults,mode=1777	0	0
          =none             /config  			      configfs  defaults		        0	0
        </content>
    </textdump>
    <!-- =================================================================== -->    
    <textdump>
      <file>hostname</file>
        <content>
          =&hostname;.&domain;
        </content>
    </textdump>
    <!-- =================================================================== -->    
    <textdump>
      <file>hosts</file>
        <content>
          =127.0.0.1 localhost.localdomain localhost &hostname;
          =10.0.0.1  &hostname;.&domain;
        </content>
    </textdump>
    <!-- =================================================================== -->    
    <textdump>
      <file>inetd.conf</file>
        <content>
          =ftp		stream	tcp nowait	    root.root /usr/sbin/ftpd ftpd -a
          =swat		stream	tcp nowait.400	root.root /usr/sbin/swat swat
        </content>
    </textdump>
    <!-- =================================================================== -->    
    <textdump>
      <file>shells</file>
        <content>
          =# /etc/shells: valid login shells
          =/bin/ash
          =/bin/sh
          =/bin/zsh
          =/bin/bash
          =/usr/bin/zsh
          =/usr/bin/bash
          =/usr/bin/screen
        </content>
    </textdump>
    <!-- =================================================================== -->
    <textdump>
      <file>inittab</file>
        <content>
          =::sysinit:/etc/init.d/rcS
          =
          =# This will run a shell on the console, usually located on ttyS0. Should not be
          =# used since Ctrl+C and similar will not work.
          =ttyS0::respawn:-/bin/sh
          =
          =# Prompts logins on ttyS0 (ask user for login and password), console above must
          =# be disabled before this is enabled.
          =#ttyS0::respawn:/sbin/getty -L 115200 ttyS0
          =# Prompts logins on ttyS2 (ask user for login and password)
          =#ttyS2::respawn:/sbin/getty -L 115200 ttyS2
          =
          =::restart:/sbin/init
          =
          =# When shutting down, unmount filesystems.
          =::shutdown:/bin/umount -a -r
        </content>
    </textdump>
    <!-- =================================================================== -->    
    <textdump>
      <file>resolv.conf</file>
        <content>
          =
        </content>
    </textdump>
    <!-- =================================================================== -->    
    <textdump>
      <file>modules</file>
        <content>
          =vfat
          =mmc_block
          =atmel-mci
          =
          =# Uncomment g_file_storage to add mass-storage on USB
          =#
          =# WARNING: Remember to unmount the SD-card before probing g_file_storage.
          =#          Failing to unmount before probing g_file_storage can corrupt
          =#          your SD-card when accessed through the USB.
          =#g_file_storage file=/dev/mmcblk0p1 removable=1
        </content>
    </textdump>
    <!-- =================================================================== -->    
  </stage>
</alfs>

=== marcelobarrosalmeida/avr32fs/stage1/devfiles.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <stage name="dev files">
    <stageinfo>
      <base>&root_dir;/dev</base>
    </stageinfo>
    <execute command="mknod">
      <param>-m 600</param>
      <param>console</param>
      <param>c 5 1</param>
    </execute>
    <execute command="mknod">
      <param>-m 666</param>
      <param>null</param>
      <param>c 1 3</param>
    </execute>
    <execute command="mknod">
      <param>-m 666</param>
      <param>zero</param>
      <param>c 1 5</param>
    </execute>
    <execute command="mknod">
      <param>-m 666</param>
      <param>ptmx</param>
      <param>c 5 2</param>
    </execute>
    <execute command="mknod">
      <param>-m 666</param>
      <param>tty</param>
      <param>c 5 0</param>
    </execute>
    <execute command="mknod">
      <param>-m 444</param>
      <param>random</param>
      <param>c 1 8</param>
    </execute>
    <execute command="mknod">
      <param>-m 444</param>
      <param>urandom</param>
      <param>c 1 9</param>
    </execute>
    <ownership user="root" group="tty">
      <name>console</name>
      <name>ptmx</name>
      <name>tty</name>
    </ownership>
  </stage>
</alfs>

=== marcelobarrosalmeida/avr32fs/stage2/iptables.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <package name="iptables" version="&iptables-version;">
    <stage name="Downloading">
      <download>
        <file>&iptables-package;</file>
        <url>&iptables-url;</url>
        <destination>&download_dir;</destination>
      </download>
    </stage>
    <stage name="Unpacking">
      <unpack>
        <archive>&download_dir;/&iptables-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Patching" />
    <stage name="Compiling">
      <stageinfo>
        <base>&build_dir;/&iptables-directory;</base>
      </stageinfo>
      <make>
        <param>KERNEL_DIR=&kernel_src;</param>
        <param>CC=avr32-linux-gcc</param>
        <param>DO_IPV6=0</param>
        <param>DESTDIR=&root_dir;</param>
        <param>PREFIX=/usr</param>
      </make>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&iptables-directory;</base>
      </stageinfo>
      <make>
        <param>install</param>
        <param>KERNEL_DIR=&kernel_src;</param>
        <param>CC=avr32-linux-gcc</param>
        <param>DO_IPV6=0</param>
        <param>DESTDIR=&root_dir;</param>
        <param>PREFIX=/usr</param>
      </make>
    </stage>
    <stage name="Strip">
      <remove>&root_dir;/usr/man/man8</remove>
    </stage>
    <!--
    <stage name="Cleanup">
      <remove>&build_dir;/&iptables-directory;</remove>
    </stage>
    -->
  </package>
</alfs>

=== marcelobarrosalmeida/avr32fs/trunk/stage2/uclibc.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <package name="uclibc" version="&uclibc-version;">
    <stage name="Unpacking">
      <unpack>
        <reference>&repository_url;/&uclibc-package;</reference>
        <archive>&packages_dir;/uclibc/&uclibc-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Patching">
      <stageinfo>
	      <base>&build_dir;/&uclibc-directory;</base>
      </stageinfo>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-uclibc-makefile-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-remove-bogus-version-hack-and-just-use-asm-generic-if-it-exists-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-let-optimized-stringops-override-default-ones-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-fix-getrusage-argument-type-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-fix-__libc_fcntl64-varargs-prototype-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-fix-broken-__libc_open-declaration-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-avr32-arch-2-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-avr32-linkrelax-option-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-avr32-string-ops-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-no-create_module-on-avr32-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-ldso-always-inline-_dl_memcpy-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-ldso-define-MAP_FAILED-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-ldso-always-inline-syscalls-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-ldso-avr32-2-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-ldso-avr32-needs-CONSTANT_STRING_GOT_FIXUP-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-ldso-avr32-startup-hack-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-ldd-ldd-avr32-support-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-libpthread-avr32-patch;</param>
      </patch>
      <patch>
      	<param>-p1</param>
      	<param>-i &packages_dir;/uclibc/&uclibc-sync-fcntl-h-with-linux-kernel-patch;</param>
      </patch>
    </stage>
    <stage name="Compiling">
      <stageinfo>
        <base>&build_dir;/&uclibc-directory;</base>
      </stageinfo>
      <copy>
        <option>force</option>
        <source>&packages_dir;/uclibc/uClibc-dot-config</source>
        <destination>.config</destination>
      </copy>
      <make>
        <param>oldconfig</param>
      </make>
      <make>
        <param>KERNEL_SOURCE=&kernel_src;</param>
      </make>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&uclibc-directory;</base>
      </stageinfo>
      <make>
        <param>install_runtime</param>
        <param>DESTDIR=&root_dir;</param>
      </make>
    </stage>
    <!--
    <stage name="Strip">
      <remove>&build_dir;/&uclibc-directory;</remove>
    </stage>
    -->
    <!--
    <stage name="Cleanup">
      <remove>&build_dir;/&uclibc-directory;</remove>
    </stage>
    -->
  </package>
</alfs>

=== marcelobarrosalmeida/avr32fs/stage1/rcfiles.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <stage name="rc files">
    <stageinfo>
      <base>&root_dir;/etc/init.d</base>
    </stageinfo>
    <!-- =================================================================== -->
    <textdump>
      <file>rcS</file>
        <content>
#!/bin/sh

/etc/init.d/S01mountvirtfs
/etc/init.d/S02hostname
/etc/init.d/S08loopback
/etc/init.d/S09syslog
/etc/init.d/S09klog
/etc/init.d/S10mdev
/etc/init.d/S10modules-init
/etc/init.d/S35mountall

if /etc/init.d/S10networking; then
	echo " * network ...                   [ OK ]"
	/etc/init.d/S11iptables
#	/etc/init.d/S15dnsmasq
#	/etc/init.d/S23ntp
	/etc/init.d/S20ssh
#	/etc/init.d/S20telnet
	/etc/init.d/S20inetd
#	/etc/init.d/S20samba
#	/etc/init.d/S91httpd
else
	echo " * Network ...                   [ FAILED ]"
fi

/etc/init.d/S99gpio

echo
echo "Network Gateway ready"
echo

exit 0
        </content>
    </textdump>
    <!-- =================================================================== -->
    <copy>
      <option>archive</option>
      <source>&skel_dir;/etc/init.d/*</source>
      <destination>.</destination>
    </copy>
    <ownership user="root" group="root">
      <name>*</name>
    </ownership>
    <permissions mode="0755">
      <name>*</name>
    </permissions>
  </stage>
</alfs>

=== marcelobarrosalmeida/avr32fs/trunk/ngw.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!--
	AVR32 Build System
-->
<!DOCTYPE alfs SYSTEM "DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "config/general.ent">
%general_entities;
]>
<alfs version="3.1" xmlns:xi="http://www.w3.org/2001/XInclude">
  <stage name="Stage 1: creating file system skeleton">
    <xi:include href="stage1/skeleton.xml" />
    <xi:include href="stage1/etcfiles.xml" />
    <xi:include href="stage1/devfiles.xml" />
    <xi:include href="stage1/rcfiles.xml"  />
  </stage>
  <stage name="Stage 2: compiling packages">
    <xi:include href="stage2/uclibc.xml" />
    <xi:include href="stage2/linux.xml" />
    <xi:include href="stage2/busybox.xml" />
    <xi:include href="stage2/zlib.xml" />
    <xi:include href="stage2/dropbear.xml" />
    <xi:include href="stage2/iptables.xml" />
  </stage>
  <stage name="Stage 3: creating image">
    <xi:include href="stage3/jffs2.xml" />
  </stage>
</alfs>

=== marcelobarrosalmeida/avr32fs/stage2/busybox.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <package name="busybox" version="&busybox-version;">
    <stage name="Unpacking">
      <unpack>
        <reference>&repository_url;/&busybox-package;</reference>
        <archive>&packages_dir;/busybox/&busybox-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Patching">
      <stageinfo>
	      <base>&build_dir;/&busybox-directory;</base>
      </stageinfo>
      <patch>
      <param>-p1</param>
      <param>-i &packages_dir;/busybox/&busybox-install-should-unlink-dest-if-it-exists-patch;</param>
      </patch>
    </stage>
    <stage name="Compiling">
      <stageinfo>
        <base>&build_dir;/&busybox-directory;</base>
      </stageinfo>
      <copy>
        <option>force</option>
        <source>&packages_dir;/busybox/busybox-dot-config</source>
        <destination>.config</destination>
      </copy>
      <make>
        <param>oldconfig</param>
      </make>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&busybox-directory;</base>
      </stageinfo>
      <make>
        <param>install</param>
        <param>PREFIX=&root_dir;/</param>
      </make>
    </stage>
    <!--
    <stage name="Strip">
      <remove>&build_dir;/&busybox-directory;</remove>
    </stage>
    -->
    <!--
    <stage name="Cleanup">
      <remove>&build_dir;/&busybox-directory;</remove>
    </stage>
    -->
  </package>
</alfs>
